name: vton_auth
version: 1.0.0+1
description: Minimal Flutter web auth flow with JWT.
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  model_viewer_plus: ^1.9.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
